### ISSUE TITLE
When using the emoji the layout gets disappeard.

### ISSUE THREAD

**Issue by sivamuralidhar3** [naturalistic/RaiseKeyboard#1]
Hi @naturalistic 

the code works great,thanks for it. but while going on some testings there's a bug.
When trying to enter emoji the above layout  moving top .

**Comment by naturalistic** [comment]
Hi @sivamuralidhar3 

Try it out now, I have fixed the issue and improved the animation.

**Comment by sivamuralidhar3** [comment]
hi @naturalistic 
thanks for fixing the issue. again i have encountered with another bug i.e i have removed "Done" button from my keyboard after removing it is showing like this
![screen shot 2016-07-16 at 12 29 55 am](https://cloud.githubusercontent.com/assets/18547242/16885570/cbdfeebe-4aec-11e6-8a78-5978b91a6674.png)
